### ISSUE TITLE
Filter is not working for long datatype fields, no response when using on lond type field 

### ISSUE THREAD

**Issue by muhammadali99** [arslanaybars/Fop#13]
Filter is not working for long datatype fields, no response when using on long type field

**Comment by arslanaybars** [comment]
I will check about it

**Comment by muhammadali99** [comment]
Thanks 😊

**Comment by cursorme** [comment]
Hi, I also think is not working for decimal data types. Is this a known limitation ?

**Comment by arslanaybars** [comment]
Tomorrow, I will add an implementation for long and decimal types! keep in touch.

**Comment by arslanaybars** [comment]
@muhammadali99  @cursorme sorry for the late update. 

Now Fop has supported more numeric types! (decimal, long, double, float, int)  ✌️

Please download and review version 1.0.1.7 and let me know me about your issue!

**Comment by cursorme** [comment]
Thanks a lot for your work and feedback. We will take a look and give you some feedback.
