### ISSUE TITLE
Case insensitive string comparisons

### ISSUE THREAD

**Issue by avidenic** [arslanaybars/Fop#14]
Hi!

First I'd like to thank you for your work. 

Different ORMs and different providers for those ORMs generate different SQL statements for string comparisons. Different DBs treat those statements differently (some are case sensitive, some are not). I propose that there is either a switch or a part of a filter where case sensitivity can be explicitly set to true or false. My idea is that this is then applied as either `.ToUpper()` or `.ToLower()` inside `StringDataTypeStrategy.cs`.
Most providers know how to project `.ToLower()` or `.ToUpper()` to a proper SQL statement. 

What do you think?

Best regards,
Anže

**Comment by arslanaybars** [comment]
Hi Anže, 👋

Now the string strategy works as case sensitive. If you need work without case sensitivity, you can pass string filter value ```lower``` or ```upper``` isn't it ok? 🤝

even if we explicit sensitivity flag. How do we know which chars are upper or lower in our string?

Thank you for your comment.

**Comment by arslanaybars** [comment]
@avidenic I am closing to issue? i

**Comment by avidenic** [comment]
Hi, 

I must have missed the feature. How can I pass string filter `lower` or `upper`?

**Comment by arslanaybars** [comment]
you need to pass the value while creating fop request.
