### ISSUE TITLE
Is there a way to filter a collection like the sql operation " IN ()"

### ISSUE THREAD

**Issue by standuptall** [arslanaybars/Fop#20]
As the subject says, Is there a way to filter a collection like I would do in sql:

SELECT *
FROM Students 
WHERE ID IN (1,2,3)

Thank you!

**Comment by arslanaybars** [comment]
Hello @standuptall 👋,

For now _fop_ doesn't support IN keyword. 

We may add this feature. 👍 I am adding this to my backlog. I will do it soon as possible.

**Comment by ith-lmsandoval** [comment]
I think it could be done just using a set of filters and the `or` logic operator.
Something like:
```
?Filter=Id==1;Id==2;Id==3;or
```
