### ISSUE TITLE
Support for .net core 6

### ISSUE THREAD

**Issue by Vrushi007** [arslanaybars/Fop#25]
Hi,
I have a project which is being ported to .netcore 6 from .netcore3.1.

I saw in documentation that it supports only .netcore3.1.

When can I expect the feature to be included?

**Comment by VitorCorrei4** [comment]
There is a pr with some small improvements, one of them is support for .Net 6.0

**Comment by arslanaybars** [comment]
Now we supports ,net 6 thanks for contribution @VitorCorrei4 

see: https://github.com/arslanaybars/Fop/pull/24
