### ISSUE TITLE
ApplyFop() is returning null when used with .netcore 6 project.

### ISSUE THREAD

**Issue by Vrushi007** [arslanaybars/Fop#28]
dbContext.<table>.ApplyFop(request); is **returning null** when the **latest package (v1.0.3)** is used in a project built using **.netcore 6**.

**Comment by VitorCorrei4** [comment]
Please provide for code  : 
            `var (filteredOrders, totalCount) = data.ApplyFop(request);`
The following : 
`var JsonData = JsonConvert.SerializeObject(data);
var JsonIFopRequest = JsonConvert.SerializeObject(request);
`
And if possible the class to deserialize JsonData
